NikolayLukashevich Hw2 Task 3
javaGuruBY/java-free-stream-2 pull request #125
Opened 2020-02-26 21:04 UTC by NikolayLukashevich

please check my work

2020-02-26 21:52 UTC, AnastasiaKichaeva requested changes

2020-02-26 21:52 UTC, AcyaKi commented on homeWork_02/ex3_ArithmeticOperations/NikolayLukashevichHw2Task3/src/by/nikalaylukashevich/mathoperationdemo.java
> +    public static void  main (string [] args ) {
"string" с большой буквы и код заработает

2020-02-27 15:56 UTC, SergeyK92 submitted a review, later dismissed

2020-02-27 23:17 UTC, AnastasiaKichaeva approved these changes

2020-02-28 21:05 UTC, SergeyK92 approved these changes

2020-03-02 08:39 UTC, DimaKachenya approved these changes
Lgfm

2020-03-02 08:39 UTC, DimaKachenya commented on homeWork_02/ex3_ArithmeticOperations/NikolayLukashevichHw2Task3/src/by/nikalaylukashevich/mathoperationdemo.java
> +public class mathoperationdemo {
Класс , по правилам , надо назвать  MathOperationDemo

2020-03-02 08:39 UTC, DimaKachenya commented on homeWork_02/ex3_ArithmeticOperations/NikolayLukashevichHw2Task3/src/by/nikalaylukashevich/mathoperationdemo.java
> +        System.out.println(b);
Можно было бы все в одну строку написать

2020-03-04 08:59 UTC, merged