Adding my first homework
javaGuruBY/java-free-stream-2 pull request #14
Opened 2020-02-19 20:13 UTC by Maria150

2020-02-19 20:32 UTC, AlexanderSmirnov92 commented on homeWork_01/Maria_Ulyanova/objects.txt
> +  илллюзия
Это как?

2020-02-19 20:34 UTC, AlexxKimm submitted a review, later dismissed

2020-02-19 20:34 UTC, AlexxKimm commented on homeWork_01/Maria_Ulyanova/objects.txt
> +  разбегается
В смысле разбегается?)))

2020-02-19 20:34 UTC, AlexxKimm commented on homeWork_01/Maria_Ulyanova/objects.txt
> + Сосояние :
Состояние

2020-02-19 21:03 UTC, a-vov4eg reviewed
look for a comments

2020-02-19 21:03 UTC, a-vov4eg commented on homeWork_01/Maria_Ulyanova/objects.txt
> +  неисправный
Это можно записать одной строкой, типа "исправный / неисправный". Добавь дополнительных состояний, типа заправлен, загружен, цвет, тип ВС и т.д.

2020-02-19 21:03 UTC, a-vov4eg commented on homeWork_01/Maria_Ulyanova/objects.txt
> +   бетонная
Тоже можно записать в одну строку, сформулировав состояние как "тип ВПП". Добавь ещё состояний, например "категория ВПП" и т.д.

2020-02-19 21:03 UTC, a-vov4eg commented on homeWork_01/Maria_Ulyanova/objects.txt
> +  холодный
относится к состоянию. К поведению можно отнести "греется, стынет, выпускает пар"

2020-02-19 21:04 UTC, a-vov4eg commented on homeWork_01/Maria_Ulyanova/objects.txt
> +  разбегается
> В смысле разбегается?)))

На обыденно языке - взлетает

2020-02-20 10:26 UTC, SerGamEsNIUS submitted a review, later dismissed
Добавь ещё 6 объектов

2020-02-20 13:30 UTC, vladis1350 requested changes

2020-02-20 13:30 UTC, vladis1350 commented on homeWork_01/Maria_Ulyanova/objects.txt
> +   бетонная
Длина
Ширина
Количество полос

2020-02-20 20:09 UTC, wnb911 submitted a review, later dismissed

2020-02-20 20:39 UTC, Alexhorosko submitted a review, later dismissed

2020-02-20 20:42 UTC, AnastasiaKichaeva submitted a review, later dismissed

2020-02-20 20:45 UTC, aleksandramazuryk submitted a review, later dismissed
All is good.

2020-02-20 21:44 UTC, javaGuruBY requested changes
переместить  файл в папку с домашним заданием

2020-02-21 10:50 UTC, NikolayLukashevich approved these changes
ok

2020-02-21 11:56 UTC, wnb911 approved these changes

2020-02-21 12:15 UTC, AnastasiaKichaeva approved these changes

2020-02-21 12:58 UTC, wnb911 approved these changes

2020-02-21 13:23 UTC, Soptimus approved these changes

2020-02-21 15:02 UTC, wnb911 approved these changes

2020-02-27 16:56 UTC, javaGuruBY approved these changes
lgfm

2020-02-27 16:56 UTC, merged