Create types
javaGuruBY/java-free-stream-2 pull request #29
Opened 2020-02-20 08:59 UTC by DimaKachenya

2020-02-21 19:21 UTC, javaGuruBY requested changes
выбери один наиболее подходящий по твоему усмотрению тип

2020-02-25 23:22 UTC, Maria150 approved these changes

2020-02-27 16:33 UTC, javaGuruBY commented on homeWork_02/ex2_Types/dima_kachenya/types
> +byte
https://neftegaz.ru/science/transportation/331683-krupneyshie-porty-mira-singapur/

5000 судов в byte не поместятся ) я бы делал short

2020-02-27 16:33 UTC, javaGuruBY commented on homeWork_02/ex2_Types/dima_kachenya/types
> +float
double 
деньги любят точность

2020-02-27 16:34 UTC, javaGuruBY commented on homeWork_02/ex2_Types/dima_kachenya/types
> +float
double - опять же: здесь важна точность

2020-02-27 16:34 UTC, javaGuruBY approved these changes
lgfm

2020-02-27 16:35 UTC, merged