Maksim rynkov hw1 task2
javaGuruBY/java-free-stream-2 pull request #4
Opened 2020-02-19 13:21 UTC by maximzmei

Review my homework please!

2020-02-19 13:30 UTC, SerGamEsNIUS requested changes
Карточку забери из банкомата!

2020-02-19 13:50 UTC, SerGamEsNIUS submitted a review, later dismissed
Looks good for me

2020-02-19 18:45 UTC, NikolayLukashevich requested changes

2020-02-19 18:45 UTC, NikolayLukashevich commented on homeWork_01/ex2_Algorithm/algorithm.txt
> +  взять йогурт и зохавать.
Алгоритм оценки, предполагает есть продукты?

2020-02-19 19:42 UTC, vladis1350 submitted a review, later dismissed

2020-02-19 19:42 UTC, vladis1350 commented on homeWork_01/ex2_Algorithm/algorithm.txt
> +  выбрать язык на экране
выбрать функцию (выдача наличных, сумма на счете, выписка по счету)
если выдача наличных

2020-02-19 20:19 UTC, TLittleProgrammer submitted a review, later dismissed

2020-02-19 20:19 UTC, Bell-Kranal commented on homeWork_01/ex2_Algorithm/algorithm.txt
> +  if time >= 2 часа дня, то быстро встать и опоздав, бежать на работу
Не используйте команды какого-либо языка. Лучше словами напишите.

2020-02-19 20:19 UTC, Bell-Kranal commented on homeWork_01/ex2_Algorithm/algorithm.txt
> +  if garbage_bag >= 10 do почистить мусорный мешок в пылесосе
Переменную лучше было бы назвать garbageBagSize.

2020-02-19 20:54 UTC, maximzmei commented on homeWork_01/ex2_Algorithm/algorithm.txt
> +  if garbage_bag >= 10 do почистить мусорный мешок в пылесосе
изменю только потому, что вы сказали. Спасибо.

2020-02-19 21:35 UTC, maximzmei commented on homeWork_01/ex2_Algorithm/algorithm.txt
> +  if time >= 2 часа дня, то быстро встать и опоздав, бежать на работу
> Не используйте команды какого-либо языка. Лучше словами напишите.

окей. Спасибо

2020-02-19 21:35 UTC, maximzmei commented on homeWork_01/ex2_Algorithm/algorithm.txt
> +  выбрать язык на экране
> выбрать функцию (выдача наличных, сумма на счете, выписка по счету)
> если выдача наличных

Updated

2020-02-19 21:35 UTC, maximzmei commented on homeWork_01/ex2_Algorithm/algorithm.txt
> +  взять йогурт и зохавать.
> Алгоритм оценки, предполагает есть продукты?

Ошибся. Пересмотрел. Спасибо большое.

2020-02-20 02:08 UTC, DimaKachenya commented on homeWork_01/ex2_Algorithm/algorithm.txt
> +  if garbage_bag >= 10 do почистить мусорный мешок в пылесосе
https://habr.com/ru/post/113044/

2020-02-20 06:35 UTC, NikolayLukashevich approved these changes
ok now.

2020-02-20 09:11 UTC, maximzmei commented on homeWork_01/ex2_Algorithm/algorithm.txt
> +  if garbage_bag >= 10 do почистить мусорный мешок в пылесосе
> https://habr.com/ru/post/113044/

я избавился уже от таких переменных, и спасибо за статью, полезно.

2020-02-20 09:44 UTC, DimaKachenya approved these changes

2020-02-20 09:44 UTC, DimaKachenya commented on homeWork_01/ex2_Algorithm/algorithm.txt
> +  if garbage_bag >= 10 do почистить мусорный мешок в пылесосе
не за что )

2020-02-20 09:46 UTC, SerGamEsNIUS approved these changes
Lgfm

2020-02-20 09:48 UTC, merged