Alexandr ushakov
javaGuruBY/java-free-stream-2 pull request #93
Opened 2020-02-24 12:47 UTC by podlw

2020-02-24 12:51 UTC, NikolayLukashevich requested changes
см. коментарии.
Файлы нужно отправить отдельно на ревью. По заданию 1 всё ок, по второму вопросы

2020-02-24 12:51 UTC, NikolayLukashevich commented on homeWork_01/ex2_Algorithm/alexandr_ushakov/alorithms.txt
> +2. достать слона
В алгоритме не описано как туда попал слон

2020-02-24 12:51 UTC, NikolayLukashevich commented on homeWork_01/ex2_Algorithm/alexandr_ushakov/alorithms.txt
> +- Рецепт приготовления теста
Скопировано из образца задания

2020-02-24 12:51 UTC, NikolayLukashevich commented on homeWork_01/ex2_Algorithm/alexandr_ushakov/alorithms.txt
> +- Посадить растение
Скопировано из образца задания

2020-02-24 12:51 UTC, NikolayLukashevich commented on homeWork_01/ex2_Algorithm/alexandr_ushakov/alorithms.txt
> +- Покупка билета в кино
Скопировано из образца задания

2020-02-24 12:52 UTC, navigan approved these changes

2020-02-24 12:52 UTC, navigan commented on homeWork_01/ex1_ObjectsAroundUs/alexandr_ushakov/objects.txt
> +		умереть
смешно, но кажется можно лучше описать)

2020-02-24 12:53 UTC, navigan commented
gfm

2020-02-24 12:54 UTC, navigan reviewed
Надо доработать все замечания

2020-02-24 12:55 UTC, navigan requested changes
Надо внести изменения в файлы.

2020-02-27 16:39 UTC, javaGuruBY approved these changes
lgfm

2020-02-27 16:39 UTC, merged